// Artist Flow Profiles — minimal version with key artists
export interface FlowProfile {
  artistId: string;
  vocalTags: string[];
  cadence: CadenceType;
  cadenceInstruction: string;
  syllablesPerBar: number;
  speedLabel: string;
  breathEveryBars: number;
  breathStyle: string;
  accentPattern: string;
  defaultRhymeScheme: string;  // rs_free, rs_aabb, rs_abab, rs_abba, rs_monorhyme, rs_internal, rs_triplets
}

export type CadenceType =
  | "triplet" | "staccato" | "legato" | "swing" | "syncopated"
  | "rapid_fire" | "melodic_flow" | "chaotic" | "conversational" | "free";

export const FLOW_PROFILES: Record<string, FlowProfile> = {
  future: { artistId: "future", vocalTags: ["auto-tune heavy", "melodic male vocal", "low-mid register", "slurred delivery", "emotional tone"], cadence: "legato", cadenceInstruction: "Flow LEGATO: alarga las sílabas, conecta las palabras de forma fluida y arrastrada. Imita el efecto del lean: lento, pesado, melódico.", syllablesPerBar: 8, speedLabel: "slow drag (lean flow)", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento en la última sílaba, alargada melódicamente" },
    defaultRhymeScheme: "rs_monorhyme",
  young_thug: { artistId: "young_thug", vocalTags: ["high pitched male vocal", "auto-tune", "eccentric melody", "slime delivery", "unpredictable pitch"], cadence: "chaotic", cadenceInstruction: "Flow CAÓTICO: rompe la métrica tradicional. Cambia de tono impredeciblemente. Melodías caprichosas.", syllablesPerBar: 10, speedLabel: "erratic melodic", breathEveryBars: 3, breathStyle: "[GASP]", accentPattern: "Acentos impredecibles" },
    defaultRhymeScheme: "rs_free",
  "21_savage": { artistId: "21_savage", vocalTags: ["low register male vocal", "whisper rap", "monotone delivery", "cold tone", "minimal inflection"], cadence: "staccato", cadenceInstruction: "Flow STACCATO: sílabas cortas y secas. MONÓTONO — sin subidas de tono. Habla como si susurraras amenazas.", syllablesPerBar: 6, speedLabel: "cold staccato", breathEveryBars: 4, breathStyle: "[PAUSE]", accentPattern: "Acento seco en consonantes, sin variación" },
    defaultRhymeScheme: "rs_aabb",
  playboi_carti: { artistId: "playboi_carti", vocalTags: ["high pitched male vocal", "baby voice", "vamp delivery", "repetitive ad-libs", "chaotic energy"], cadence: "chaotic", cadenceInstruction: "Flow VAMP: repite palabras obsesivamente. Tono agudo, casi infantil. Mínimo contenido, máxima vibra.", syllablesPerBar: 6, speedLabel: "vamp repetition", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento en ad-libs más que en contenido" },
    defaultRhymeScheme: "rs_monorhyme",
  gunna: { artistId: "gunna", vocalTags: ["melodic male vocal", "smooth delivery", "mid-high register", "auto-tune light", "effortless flow"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO: cada barra es casi cantada. 'Drip' — cada palabra suena cara.", syllablesPerBar: 9, speedLabel: "smooth melodic drip", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento melódico en vocales finales" },
    defaultRhymeScheme: "rs_abab",
  lil_baby: { artistId: "lil_baby", vocalTags: ["mid register male vocal", "rapid melodic", "strained voice", "emotional delivery", "breathless flow"], cadence: "melodic_flow", cadenceInstruction: "Flow RAPID MELODIC: rápido pero cantado. Voz ligeramente forzada. Confesional.", syllablesPerBar: 12, speedLabel: "rapid melodic confessional", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento emocional, sube en punchlines" },
    defaultRhymeScheme: "rs_abab",
  drake: { artistId: "drake", vocalTags: ["versatile male vocal", "mid register", "singing-rapping hybrid", "emotional tone", "clean delivery"], cadence: "conversational", cadenceInstruction: "Flow CONVERSATIONAL: habla-rapa como si contaras algo a un amigo. Alterna entre rapeo hablado y frases cantadas.", syllablesPerBar: 10, speedLabel: "conversational versatile", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento natural de conversación" },
    defaultRhymeScheme: "rs_abab",
  travis_scott: { artistId: "travis_scott", vocalTags: ["auto-tune heavy", "psychedelic male vocal", "atmospheric delivery", "reverb vocal", "rage energy"], cadence: "syncopated", cadenceInstruction: "Flow SYNCOPADO con ATMÓSFERA: acentos fuera del tiempo. Ad-libs catastróficos. Energía de moshpit.", syllablesPerBar: 11, speedLabel: "psychedelic syncopated", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acentos off-beat, ad-libs explotan al final" },
    defaultRhymeScheme: "rs_abab",
  don_tolver: { artistId: "don_tolver", vocalTags: ["high register male vocal", "falsetto", "R&B smooth", "seductive tone", "auto-tune melodic"], cadence: "melodic_flow", cadenceInstruction: "Flow R&B MELODICO: casi todo cantado. Usa falseteo en frases clave. Suave, seductor.", syllablesPerBar: 10, speedLabel: "smooth R&B falsetto", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento en notas altas (falseteo)" },
    defaultRhymeScheme: "rs_abab",
  lil_uzi: { artistId: "lil_uzi", vocalTags: ["high pitched male vocal", "emo rap delivery", "energetic", "melodic punk", "auto-tune"], cadence: "rapid_fire", cadenceInstruction: "Flow RAPID FIRE MELODIC: rápido, energético, casi punk. Tono agudo, juvenil. Emocional.", syllablesPerBar: 14, speedLabel: "emo rapid fire", breathEveryBars: 2, breathStyle: "[GASP]", accentPattern: "Acento en la 1ª sílaba, energía creciente" },
    defaultRhymeScheme: "rs_aabb",
  yeat: { artistId: "yeat", vocalTags: ["deep male vocal", "aggressive delivery", "distorted vocal", "rage energy", "tongue clicking"], cadence: "staccato", cadenceInstruction: "Flow STACCATO RAGE: sílabas duras como martillazos. Tono grave y distorsionado. Repetitivo.", syllablesPerBar: 7, speedLabel: "rage staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento percusivo en cada sílaba" },
    defaultRhymeScheme: "rs_monorhyme",
  eminem: { artistId: "eminem", vocalTags: ["aggressive male vocal", "nasal delivery", "rapid fire", "technical rap", "angry tone"], cadence: "rapid_fire", cadenceInstruction: "Flow RAPID FIRE TÉCNICO: ametralladora de sílabas. Rimas internas multi-silábicas. Acelera y frena dramáticamente.", syllablesPerBar: 16, speedLabel: "rapid fire technical", breathEveryBars: 4, breathStyle: "[BREATH]", accentPattern: "Acento en cada rima interna" },
    defaultRhymeScheme: "rs_internal",
  j_cole: { artistId: "j_cole", vocalTags: ["mid register male vocal", "conscious rap delivery", "natural tone", "storytelling voice"], cadence: "conversational", cadenceInstruction: "Flow CONVERSATIONAL CONSCIOUS: habla como si contaras una historia real. Natural, sin artificios.", syllablesPerBar: 11, speedLabel: "conscious storytelling", breathEveryBars: 3, breathStyle: "[PAUSE]", accentPattern: "Acento natural de habla" },
    defaultRhymeScheme: "rs_abab",
  kendrick: { artistId: "kendrick", vocalTags: ["versatile male vocal", "dynamic range", "aggressive to melodic", "character voices", "intense delivery"], cadence: "syncopated", cadenceInstruction: "Flow VERSÁTIL DINÁMICO: cambia de flow cada 4 barras. Pasa de susurro a grito. Usa voces de personaje.", syllablesPerBar: 12, speedLabel: "dynamic shape-shifter", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acentos cambiantes, imita personajes" },
    defaultRhymeScheme: "rs_internal",
  quavo: { artistId: "quavo", vocalTags: ["auto-tune melodic male vocal", "mid-high register", "migos triplet flow", "hook delivery", "smooth tone"], cadence: "triplet", cadenceInstruction: "Flow TRIPLET MELODIC: agrupa las sílabas en 3 por beat (da-da-DA). Es el más melódico de Migos: hace hooks y melodías.", syllablesPerBar: 11, speedLabel: "triplet melodic bounce", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento en la 3ª sílaba de cada grupo triplet" },
    defaultRhymeScheme: "rs_triplets",
  offset: { artistId: "offset", vocalTags: ["aggressive male vocal", "mid-low register", "migos triplet flow", "sharp delivery", "street tone"], cadence: "triplet", cadenceInstruction: "Flow TRIPLET AGRESIVO: agrupa en 3 por beat con golpe SECO y cortante. El más calle de Migos: punchlines, flow amenazante.", syllablesPerBar: 11, speedLabel: "triplet aggressive street", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento percusivo en la 1ª sílaba" },
    defaultRhymeScheme: "rs_triplets",
  takeoff: { artistId: "takeoff", vocalTags: ["deep male vocal", "low register", "migos triplet flow", "technical dense delivery", "metronomic rhythm"], cadence: "triplet", cadenceInstruction: "Flow TRIPLET TÉCNICO: agrupa en 3 por beat con precisión metronómica. El más técnico de Migos (QEPD): rimas internas densas, flow perfecto.", syllablesPerBar: 13, speedLabel: "triplet technical dense", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento en cada grupo triplet, precisión metronómica" },
    defaultRhymeScheme: "rs_triplets",
  gucci_mane: { artistId: "gucci_mane", vocalTags: ["mid register male vocal", "Atlanta pioneer delivery", "grave tone", "classic trap", "raw street"], cadence: "staccato", cadenceInstruction: "Flow STACCATO ATLANTA: sílabas marcadas con acento sureño. Pionero del trap. Ad-libs icónicos (Brrr, It's Gucci).", syllablesPerBar: 9, speedLabel: "classic atlanta staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento sureño marcado" },
    defaultRhymeScheme: "rs_aabb",
  pop_smoke: { artistId: "pop_smoke", vocalTags: ["deep gravelly male vocal", "Brooklyn drill delivery", "raspy tone", "menacing", "low register"], cadence: "syncopated", cadenceInstruction: "Flow SYNCOPATED DRILL: voz grave y rasposa. Acentos en lugares inesperados. Pausas dramáticas antes de punchlines.", syllablesPerBar: 9, speedLabel: "Brooklyn drill raspy", breathEveryBars: 3, breathStyle: "[PAUSE]", accentPattern: "Acento rasposo en consonantes" },
    defaultRhymeScheme: "rs_aabb",
  chief_keef: { artistId: "chief_keef", vocalTags: ["young male vocal", "Chicago drill delivery", "lazy flow", "auto-tune", "monotone melodic"], cadence: "legato", cadenceInstruction: "Flow LEGATO LAZY: perezoso, arrastrado, detrás del beat. Tono joven, casi aburrido.", syllablesPerBar: 8, speedLabel: "lazy Chicago drill", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento perezoso en la 1ª sílaba" },
    defaultRhymeScheme: "rs_monorhyme",
  yung_beef: { artistId: "yung_beef", vocalTags: ["mid register male vocal", "Spanish accent", "raw aggressive delivery", "barrio tone", "Barcelona slang"], cadence: "staccato", cadenceInstruction: "Flow STACCATO BARCELONA: crudo, calle, sin filtro. Slang del 2001 (kekos, prrr). Voz rasposa, agresiva.", syllablesPerBar: 7, speedLabel: "barrio staccato crudo", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento barrial en consonantes" },
    defaultRhymeScheme: "rs_aabb",
  cruz_cafune: { artistId: "cruz_cafune", vocalTags: ["melodic male vocal", "Canary Islands accent", "warm tone", "reflective delivery", "smooth"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO CANARIO: suave, reflexivo, con acento isleño. Slang canario (pana, nene).", syllablesPerBar: 10, speedLabel: "canario melodic warm", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento canario suave en vocales" },
    defaultRhymeScheme: "rs_abab",
  quevedo: { artistId: "quevedo", vocalTags: ["melodic male vocal", "young tone", "Canary Islands-Madrid accent", "catchy delivery", "auto-tune light"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO JOVEN: pegadizo, bailable, tono juvenil. Slang canario-madrileño.", syllablesPerBar: 10, speedLabel: "young catchy melodic", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento pegadizo en rimas" },
    defaultRhymeScheme: "rs_abab",
  bad_bunny: { artistId: "bad_bunny", vocalTags: ["deep raspy male vocal", "Puerto Rican accent", "versatile delivery", "unique tone", "lazy flow"], cadence: "legato", cadenceInstruction: "Flow LEGATO VERSÁTIL: arrastrado pero versátil. Voz rasposa única. Spanglish fluido.", syllablesPerBar: 10, speedLabel: "versatile lazy drag", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento boricua arrastrado" },
    defaultRhymeScheme: "rs_abab",
  central_cee: { artistId: "central_cee", vocalTags: ["mid register male vocal", "UK drill delivery", "British accent", "melodic drill", "fast flow"], cadence: "syncopated", cadenceInstruction: "Flow SYNCOPATED UK DRILL: rápido con acento londinense. Slang británico (mandem, bruv). Acentos off-beat.", syllablesPerBar: 12, speedLabel: "UK drill fast", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento británico en tiempos débiles" },
    defaultRhymeScheme: "rs_aabb",
  anuel_aa: { artistId: "anuel_aa", vocalTags: ["deep male vocal", "auto-tune heavy", "Puerto Rican accent", "aggressive Latin trap", "menacing"], cadence: "staccato", cadenceInstruction: "Flow STACCATO LATIN TRAP: voz grave con auto-tune. Spanglish agresivo. Acento boricua.", syllablesPerBar: 8, speedLabel: "Latin trap aggressive", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento boricua grave y amenazante" },
    defaultRhymeScheme: "rs_aabb",
};

export function getFlowProfile(artistId: string): FlowProfile | null {
  return FLOW_PROFILES[artistId] ?? ADDITIONAL_FLOW_PROFILES[artistId] ?? null;
}

export function getCadenceLabel(cadence: CadenceType): string {
  const labels: Record<CadenceType, string> = {
    triplet: "Triplet (3 por beat)",
    staccato: "Staccato (sílabas secas)",
    legato: "Legato (arrastrado)",
    swing: "Swing (laid-back)",
    syncopated: "Syncopated (off-beat)",
    rapid_fire: "Rapid Fire (ametralladora)",
    melodic_flow: "Melodic Flow (cantado)",
    chaotic: "Chaotic (impredecible)",
    conversational: "Conversational (natural)",
    free: "Free (libre)",
  };
  return labels[cadence] ?? cadence;
}

export function getBreathInstruction(profile: FlowProfile): string {
  return `Inserta un ${profile.breathStyle} cada ${profile.breathEveryBars} barras aproximadamente, en el punto natural de respiración. Esto hace que Suno genere pausas vocales realistas.`;
}

// ===== ARTISTAS FALTANTES =====

export const ADDITIONAL_FLOW_PROFILES: Record<string, FlowProfile> = {
  kodak_black: { artistId: "kodak_black", vocalTags: ["nasal male vocal", "Florida drawl", "auto-tune light", "raw delivery", "slurred"], cadence: "legato", cadenceInstruction: "Flow LEGATO FLORIDA: arrastrado, nasal, con acento floridiano. Conecta palabras de forma perezosa pero rítmica. Tono único, inconfundible.", syllablesPerBar: 9, speedLabel: "Florida drag", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento nasal en vocales, arrastrado", defaultRhymeScheme: "rs_aabb" },
  juice_wrld: { artistId: "juice_wrld", vocalTags: ["melodic male vocal", "emo rap delivery", "auto-tune light", "emotional tone", "mid-high register"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO EMO: cada barra es una melodía cantada. Tono emocional, vulnerable. Improvisa frases melódicas entre versos. Rimas pegadizas de final.", syllablesPerBar: 11, speedLabel: "emo melodic", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento melódico en vocales finales, sube en emociones", defaultRhymeScheme: "rs_abab" },
  lil_pump: { artistId: "lil_pump", vocalTags: ["high energy male vocal", "shouting delivery", "distorted", "hypetrain", "ad-lib heavy"], cadence: "staccato", cadenceInstruction: "Flow STACCATO HYPE: grita frases cortas y pegadizas. Repetitivo al extremo. Ad-libs más largos que el verso. Energía de moshpit. Frases de 4-6 palabras a todo volumen.", syllablesPerBar: 6, speedLabel: "hype staccato", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento en cada palabra, todo gritado", defaultRhymeScheme: "rs_monorhyme" },
  xxxtentacion: { artistId: "xxxtentacion", vocalTags: ["versatile male vocal", "screaming to melodic", "emotional delivery", "distorted", "punk rap"], cadence: "chaotic", cadenceInstruction: "Flow CAÓTICO EMOCIONAL: extremo. Pasa de susurro melancólico a grito desgarrador en la misma barra. Inestable, crudo, vulnerable. Rompe toda estructura.", syllablesPerBar: 10, speedLabel: "emotional chaos", breathEveryBars: 2, breathStyle: "[GASP]", accentPattern: "Acentos extremos: susurros y gritos en contraste", defaultRhymeScheme: "rs_free" },
  blueface: { artistId: "blueface", vocalTags: ["off-beat male vocal", "West Coast delivery", "raspy", "unique timing", "energetic"], cadence: "syncopated", cadenceInstruction: "Flow OFF-BEAT INTENCIONAL: rapea FUERA del tiempo a propósito. Los acentos caen donde NO deberían. Es el efecto 'Blueface' — suena raro pero pegadizo.", syllablesPerBar: 9, speedLabel: "intentional off-beat", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acentos en tiempos débiles del compás, intencionalmente raro", defaultRhymeScheme: "rs_free" },
  roddy_ricch: { artistId: "roddy_ricch", vocalTags: ["melodic male vocal", "high register", "auto-tune light", "West Coast bounce", "emotional"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO BOUNCE: cada barra tiene melodía pegadiza. Sube de tono en las rimas. Bounce de la costa oeste — pegadizo pero con calle.", syllablesPerBar: 11, speedLabel: "West Coast melodic bounce", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento melódico ascendente, pegadizo", defaultRhymeScheme: "rs_abab" },
  babyface_ray: { artistId: "babyface_ray", vocalTags: ["mid register male vocal", "Detroit delivery", "laid-back flow", "conversational", "raw tone"], cadence: "conversational", cadenceInstruction: "Flow CONVERSATIONAL DETROIT: habla-rapa natural, sin esfuerzo. Tono relajado pero crudo. Detroit street — cuenta historias de scam/hustle.", syllablesPerBar: 11, speedLabel: "Detroit conversational", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento natural de conversación, relajado", defaultRhymeScheme: "rs_abab" },
  key_glock: { artistId: "key_glock", vocalTags: ["mid register male vocal", "Memphis delivery", "aggressive", "raw tone", "southern drawl"], cadence: "staccato", cadenceInstruction: "Flow STACCATO MEMPHIS: sílabas duras con acento sureño. Agresivo pero sin prisa. Ad-libs de Memphis. Frases de 7-9 sílabas golpeadas.", syllablesPerBar: 8, speedLabel: "Memphis staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento sureño en consonantes, seco", defaultRhymeScheme: "rs_aabb" },
  young_dolph: { artistId: "young_dolph", vocalTags: ["deep male vocal", "Memphis delivery", "raspy tone", "confident", "southern drawl"], cadence: "staccato", cadenceInstruction: "Flow STACCATO MEMPHIS GRAVE: voz rasposa y profunda. Tono amenazante pero relajado. Flex crudo del sur. Frases de 7-9 sílabas con golpe sureño.", syllablesPerBar: 8, speedLabel: "Memphis grave flex", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento sureño grave, confiado", defaultRhymeScheme: "rs_aabb" },
  fivio_foreign: { artistId: "fivio_foreign", vocalTags: ["mid register male vocal", "NY drill delivery", "melodic drill", "auto-tune light", "energetic"], cadence: "syncopated", cadenceInstruction: "Flow SYNCOPATED MELODIC DRILL: mezcla de drill agresivo con melodía. Acentos off-beat pero con tono cantarín. Ad-libs de fondo ('Gang!').", syllablesPerBar: 10, speedLabel: "melodic drill", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento off-beat con subida melódica en rimas", defaultRhymeScheme: "rs_aabb" },
  lil_durk: { artistId: "lil_durk", vocalTags: ["melodic male vocal", "auto-tune", "Chicago drill", "emotional delivery", "mid register"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO DRILL: drill con melodía. Auto-tune visible pero no excesivo. Tono emocional, dolor de calle. Frases que suben de melodía en las rimas.", syllablesPerBar: 11, speedLabel: "melodic drill emotional", breathEveryBars: 2, breathStyle: "[BREATH]", accentPattern: "Acento melódico ascendente en rimas finales", defaultRhymeScheme: "rs_abab" },
  polo_g: { artistId: "polo_g", vocalTags: ["melodic male vocal", "emotional delivery", "auto-tune light", "introspective", "young tone"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO INTROSPECTIVO: letra introspectiva sobre trauma y calle. Tono vulnerable pero calle. Cada barra tiene melodía sutil.", syllablesPerBar: 11, speedLabel: "introspective melodic", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento emocional en palabras de contenido", defaultRhymeScheme: "rs_abab" },
  lil_yachty: { artistId: "lil_yachty", vocalTags: ["nasal male vocal", "playful delivery", "bright tone", "auto-tune", "energetic"], cadence: "melodic_flow", cadenceInstruction: "Flow ALEGRE BURLÓN: voz nasal aguda, vamps coloridos. Estilo bubblegum trap, enérgico y optimista. Frases pegadizas y divertidas.", syllablesPerBar: 9, speedLabel: "bubblegum playful", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento juguetón en vocales, nasal", defaultRhymeScheme: "rs_aabb" },
  pnl: { artistId: "pnl", vocalTags: ["auto-tune heavy", "whispered male vocal", "cloud rap delivery", "ethereal", "melancholic French"], cadence: "legato", cadenceInstruction: "Flow LEGATO CLOUD RAP: susurrado, etéreo, melancólico. Auto-tune extremo. Voz flotando sobre el beat. Francés con auto-tune pesado.", syllablesPerBar: 10, speedLabel: "cloud rap ethereal", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento susurrado, sin énfasis, flotante", defaultRhymeScheme: "rs_free" },
  booba: { artistId: "booba", vocalTags: ["mid register male vocal", "French rap delivery", "aggressive tone", "technical", "confident"], cadence: "staccato", cadenceInstruction: "Flow STACCATO TÉCNICO FRANCÉS: sílabas marcadas, ego desbordado, punchlines cortantes. Pionero del rap francés. Tono agresivo y seguro.", syllablesPerBar: 10, speedLabel: "French technical staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento francés marcado en consonantes", defaultRhymeScheme: "rs_aabb" },
  ninho: { artistId: "ninho", vocalTags: ["melodic male vocal", "French delivery", "smooth tone", "auto-tune light", "versatile"], cadence: "melodic_flow", cadenceInstruction: "Flow MELODICO VERSÁTIL FRANCÉS: flex sutil + introspección. Tono versátil, cambia entre rap y melodía. Letras de éxito, dinero y vida personal.", syllablesPerBar: 11, speedLabel: "French melodic versatile", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento francés suave, melódico", defaultRhymeScheme: "rs_abab" },
  yovngchimi: { artistId: "yovngchimi", vocalTags: ["aggressive male vocal", "demonic delivery", "PR drill", "distorted", "screaming ad-libs"], cadence: "staccato", cadenceInstruction: "Flow STACCATO DEMONIACO: violento, crudo, endemoniado. Drill PR con voz distorsionada. Ad-libs guturales. Frases cortas y agresivas como disparos.", syllablesPerBar: 7, speedLabel: "demonic drill", breathEveryBars: 2, breathStyle: "[GASP]", accentPattern: "Acento violento en cada sílaba, como disparos", defaultRhymeScheme: "rs_aabb" },
  myke_towers: { artistId: "myke_towers", vocalTags: ["mid register male vocal", "Puerto Rican accent", "technical delivery", "smooth tone", "confident"], cadence: "syncopated", cadenceInstruction: "Flow TÉCNICO BORICUA: Spanglish balanceado, flex con elegancia. Flow técnico pero suave. Frases de 10-12 sílabas con golpe caribeño.", syllablesPerBar: 11, speedLabel: "Latin technical smooth", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento boricua técnico, seguro", defaultRhymeScheme: "rs_abab" },
  kidd_keo: { artistId: "kidd_keo", vocalTags: ["mid register male vocal", "Spanglish delivery", "dark tone", "Rockport style", "raspy"], cadence: "staccato", cadenceInstruction: "Flow STACCATO SPANGLISH: duro, oscuro, Spanglish constante. Voz rasposa. Flow Rockport — calle + autodestrucción. Frases de 7-9 sílabas con golpe seco.", syllablesPerBar: 8, speedLabel: "Spanglish dark staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento duro en Spanglish, mezcla ES/EN natural", defaultRhymeScheme: "rs_aabb" },
  morad: { artistId: "morad", vocalTags: ["mid register male vocal", "multinational accent", "raspy delivery", "raw street tone", "emotional"], cadence: "conversational", cadenceInstruction: "Flow CONVERSATIONAL MULTICULTURAL: voz rasposa, cruda. Slang multinacional (magrebí + latino + madrileño). Historias de exclusión social.", syllablesPerBar: 11, speedLabel: "multicultural testimonial", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento multinacional, énfasis en palabras de calle", defaultRhymeScheme: "rs_abab" },
  beny_jr: { artistId: "beny_jr", vocalTags: ["mid register male vocal", "magrebí influence", "raspy delivery", "Barcelona slang", "raw"], cadence: "staccato", cadenceInstruction: "Flow STACCATO MAGREBÍ: crudo con influencia magrebí, slang multinacional Barcelona, voz rasposa. Calle, lealtad y barrio.", syllablesPerBar: 8, speedLabel: "magrebí street staccato", breathEveryBars: 3, breathStyle: "[BREATH]", accentPattern: "Acento magrebí en consonantes, rasposo", defaultRhymeScheme: "rs_aabb" },
  hard_gz: { artistId: "hard_gz", vocalTags: ["low register male vocal", "Madrid drill delivery", "dark tone", "menacing", "grave"], cadence: "staccato", cadenceInstruction: "Flow STACCATO OSCURO MADRILEÑO: voz grave y oscura, slang del barrio madrileño, narrativa de calle cruda. Violencia y supervivencia.", syllablesPerBar: 8, speedLabel: "Madrid dark staccato", breathEveryBars: 3, breathStyle: "[PAUSE]", accentPattern: "Acento grave madrileño, amenazante", defaultRhymeScheme: "rs_aabb" },
  agnus_tris: { artistId: "agnus_tris", vocalTags: ["low register male vocal", "drill delivery", "menacing tone", "distorted", "threatening"], cadence: "staccato", cadenceInstruction: "Flow STACCATO DRILL MADRILEÑO: voz grave amenazante, slang del 2001, drill madrileño. Violencia explícita y territorio. Frases cortas y amenazantes.", syllablesPerBar: 7, speedLabel: "Madrid drill menacing", breathEveryBars: 2, breathStyle: "[PAUSE]", accentPattern: "Acento grave amenazante, seco", defaultRhymeScheme: "rs_aabb" },
  recycled_j: { artistId: "recycled_j", vocalTags: ["mid register male vocal", "Madrid accent", "technical delivery", "storytelling", "boom bap influence"], cadence: "swing", cadenceInstruction: "Flow TÉCNICO STORYTELLING: rimas elaboradas, multi-silábicas. Tono introspectivo, literario. Madrid urbano. Cada barra construye narrativa.", syllablesPerBar: 12, speedLabel: "technical storytelling", breathEveryBars: 3, breathStyle: "[PAUSE]", accentPattern: "Acento en palabras de contenido, pausas narrativas", defaultRhymeScheme: "rs_internal" },
};

// Merge both profile maps
const ALL_PROFILES = { ...FLOW_PROFILES, ...ADDITIONAL_FLOW_PROFILES };

// Override getFlowProfile to use merged map
export function getFlowProfileFull(artistId: string): FlowProfile | null {
  return ALL_PROFILES[artistId] ?? null;
}
